site_name: Xournal++ HTR
site_description: Developing handwritten text recognition for Xournal++

repo_name: PellelNitram/xournalpp_htr
repo_url: https://github.com/PellelNitram/xournalpp_htr
edit_uri: edit/master/docs/

theme:
  name: material

nav:
  - 'index.md'
  - 'developing_new_models.md'
  - 'roadmap.md'
  - 'contributing.md'