site_name: Xournal++ HTR
site_description: Developing handwritten text recognition for Xournal++

repo_name: PellelNitram/xournalpp_htr
repo_url: https://github.com/PellelNitram/xournalpp_htr
edit_uri: edit/master/docs/

strict: true

theme:
  name: material

nav:
  - Introduction: 'index.md'
  - Data Collection: 'data_collection.md'
  - Developing New Models: 'developing_new_models.md'
  - Roadmap: 'roadmap.md'
  - Contributing: 'contributing.md'