# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run tests

on:
  push:
    branches:
    - "master"
    - "dev"
  pull_request:
    branches:
    - "master"
    - "dev"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.11"
    - name: Install htr_pipeline package
      run: |
        mkdir -p HTR_PIPELINE_PATH
        cd HTR_PIPELINE_PATH
        git clone https://github.com/githubharald/HTRPipeline.git
        cd HTRPipeline
        cd htr_pipeline/models
        wget https://www.dropbox.com/s/j1hl6bppecug0sz/models.zip
        unzip -o models.zip
        cd ../../
        pip install .
        cd ../../ 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .
    - name: Test with pytest
      run: |
        make tests-installation
